# Generated by Django 3.1 on 2021-05-31 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('student_age', models.IntegerField(default=18)),
                ('student_birthday', models.DateField(blank=True, null=True)),
                ('student_info', models.TextField()),
            ],
        ),
    ]
